language: scala
scala:
  - 2.10.0
jdk:
  - oraclejdk7
branches:
  only:
    - master
before_script:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xms512M -Xmx2048M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=384M"
