package worksheets

import akka.dispatch.{ Await, Future }
import almhirt._
import almhirt.almvalidation.kit._
import almhirt.environment._
import test._
import almhirt.almfuture.inst._

object SequentialChunksWorksheet extends TestAlmhirtKit {
  implicit val atMost = akka.util.Duration(500, "ms")
                                                  //> atMost  : akka.util.FiniteDuration = 500 milliseconds
  inTestAlmhirt { almhirt =>
    implicit val executor = almhirt.environment.context.system.futureDispatcher
    val idsAndNamesAndAdresses = Vector((for (i <- 0 until 100) yield (i, almhirt.getUuid, "Name%s".format(i), "Address%s".format(i))): _*)

    val repo = almhirt.environment.repositories.getForAggregateRoot[TestPerson, TestPersonEvent].awaitResult.forceResult

    idsAndNamesAndAdresses.foreach(x => almhirt.executeTrackedCommand(NewTestPerson(x._2, x._3), "A insert%s".format(x._1.toString)))
    val insertStatesFutures = idsAndNamesAndAdresses.map(x => almhirt.getResultOperationStateFor("A insert%s".format(x._1.toString)))
    val insertStatesRes = AlmFuture.sequence(insertStatesFutures).awaitResult
    println("--- insert done ---")
    if (insertStatesRes.isFailure) println(insertStatesRes)
    insertStatesRes.foreach { insertStates =>
      insertStates.foreach(x => x fold (f => println(f), succ => println(succ)))
    }

    idsAndNamesAndAdresses.foreach(x => almhirt.executeTrackedCommand(SetTestPersonAddress(x._2, Some(1), x._4), "A setaddress%s".format(x._1.toString)))
    val update1StatesFutures = idsAndNamesAndAdresses.map(x => almhirt.getResultOperationStateFor("A setaddress%s".format(x._1.toString)))
    val update1StatesRes = AlmFuture.sequence(update1StatesFutures).awaitResult
    println("--- setaddress done ---")
    if (update1StatesRes.isFailure) println(update1StatesRes)
    update1StatesRes.foreach { updateStates =>
      updateStates.foreach(x => x fold (f => println(f), succ => println(succ)))
    }

    idsAndNamesAndAdresses.foreach(x => almhirt.executeTrackedCommand(MoveBecauseOfMarriage(x._2, Some(2), "namemarriage%s".format(x._3), "addressmarriage%s".format(x._3)), "A updatemarriage%s".format(x._1.toString)))
    val update2StatesFutures = idsAndNamesAndAdresses.map(x => almhirt.getResultOperationStateFor("A updatemarriage%s".format(x._1.toString)))
    val update2StatesRes = AlmFuture.sequence(update2StatesFutures).awaitResult
    println("--- updatemarriage done ---")
    if (update2StatesRes.isFailure) println(update2StatesRes)
    update2StatesRes.foreach { updateStates =>
      updateStates.foreach(x => x fold (f => println(f), succ => println(succ)))
    }


    idsAndNamesAndAdresses.foreach(x => almhirt.executeTrackedCommand(ChangeTestPersonName(x._2, Some(4), "new%s".format(x._3)), "A updatename%s".format(x._1.toString)))
    val update3StatesFutures = idsAndNamesAndAdresses.map(x => almhirt.getResultOperationStateFor("A updatename%s".format(x._1.toString)))
    val update3StatesRes = AlmFuture.sequence(update3StatesFutures).awaitResult
    println("--- updatename done ---")
    if (update3StatesRes.isFailure) println(update3StatesRes)

    //    almhirt.environment.eventLog.getAllEvents.awaitResult.forceResult.foreach(println)
    //    AlmFuture.sequence(idsAndNamesAndAdresses.map(x => repo.get(x._2))).awaitResult.forceResult.foreach(println)

    update3StatesRes.map { updateStates =>
      updateStates.foreach(x => x fold (f => println(f), succ => println(succ)))
      updateStates
    }.fold(
      f => false,
      succ => succ.forall(_.isSuccess) && succ.forall(_.forceResult.isFinishedSuccesfully))
  }                                               //> --- insert done ---
                                                  //| Executed(A insert0)
                                                  //| Executed(A insert1)
                                                  //| Executed(A insert2)
                                                  //| Executed(A insert3)
                                                  //| Executed(A insert4)
                                                  //| Executed(A insert5)
                                                  //| Executed(A insert6)
                                                  //| Executed(A insert7)
                                                  //| Executed(A insert8)
                                                  //| Executed(A insert9)
                                                  //| Executed(A insert10)
                                                  //| Executed(A insert11)
                                                  //| Executed(A insert12)
                                                  //| Executed(A insert13)
                                                  //| Executed(A insert14)
                                                  //| Executed(A insert15)
                                                  //| Executed(A insert16)
                                                  //| Executed(A insert17)
                                                  //| Executed(A insert18)
                                                  //| Executed(A insert19)
                                                  //| Executed(A insert20)
                                                  //| Executed(A insert21)
                                                  //| Executed(A insert22)
                                                  //| Executed(A insert23)
                                                  //| Executed(A insert24)
                                                  //| Executed(A insert25)
                                                  //| Executed(A insert26)
                                                  //| Executed(A insert27)
                                                  //| Executed(A insert28)
                                                  //| Executed(A insert29)
                                                  //| Executed(A insert30)
                                                  //| Executed(A insert31)
                                                  //| Executed(A insert32)
                                                  //| Executed(A insert33)
                                                  //| Executed(A insert34)
                                                  //| Executed(A insert35)
                                                  //| Executed(A insert36)
                                                  //| Executed(A insert37)
                                                  //| Executed(A insert38)
                                                  //| Executed(A insert39)
                                                  //| Executed(A insert40)
                                                  //| Executed(A insert41)
                                                  //| Executed(A insert42)
                                                  //| Executed(A insert43)
                                                  //| Executed(A insert44)
                                                  //| Executed(A insert45)
                                                  //| Executed(A insert46)
                                                  //| Executed(A insert47)
                                                  //| Executed(A insert48)
                                                  //| Executed(A insert49)
                                                  //| Executed(A insert50)
                                                  //| Executed(A insert51)
                                                  //| Executed(A insert52)
                                                  //| Executed(A insert53)
                                                  //| Executed(A insert54)
                                                  //| Executed(A insert55)
                                                  //| Executed(A insert56)
                                                  //| Executed(A insert57)
                                                  //| Executed(A insert58)
                                                  //| Executed(A insert59)
                                                  //| Executed(A insert60)
                                                  //| Executed(A insert61)
                                                  //| Executed(A insert62)
                                                  //| Executed(A insert63)
                                                  //| Executed(A insert64)
                                                  //| Executed(A insert65)
                                                  //| Executed(A insert66)
                                                  //| Executed(A insert67)
                                                  //| Executed(A insert68)
                                                  //| Executed(A insert69)
                                                  //| Executed(A insert70)
                                                  //| Executed(A insert71)
                                                  //| Executed(A insert72)
                                                  //| Executed(A insert73)
                                                  //| Executed(A insert74)
                                                  //| Executed(A insert75)
                                                  //| Executed(A insert76)
                                                  //| Executed(A insert77)
                                                  //| Executed(A insert78)
                                                  //| Executed(A insert79)
                                                  //| Executed(A insert80)
                                                  //| Executed(A insert81)
                                                  //| Executed(A insert82)
                                                  //| Executed(A insert83)
                                                  //| Executed(A insert84)
                                                  //| Executed(A insert85)
                                                  //| Executed(A insert86)
                                                  //| Executed(A insert87)
                                                  //| Executed(A insert88)
                                                  //| Executed(A insert89)
                                                  //| Executed(A insert90)
                                                  //| Executed(A insert91)
                                                  //| Executed(A insert92)
                                                  //| Executed(A insert93)
                                                  //| Executed(A insert94)
                                                  //| Executed(A insert95)
                                                  //| Executed(A insert96)
                                                  //| Executed(A insert97)
                                                  //| Executed(A insert98)
                                                  //| Executed(A insert99)
                                                  //| --- setaddress done ---
                                                  //| Executed(A setaddress0)
                                                  //| Executed(A setaddress1)
                                                  //| Executed(A setaddress2)
                                                  //| Executed(A setaddress3)
                                                  //| Executed(A setaddress4)
                                                  //| Executed(A setaddress5)
                                                  //| Executed(A setaddress6)
                                                  //| Executed(A setaddress7)
                                                  //| Executed(A setaddress8)
                                                  //| Executed(A setaddress9)
                                                  //| Executed(A setaddress10)
                                                  //| Executed(A setaddress11)
                                                  //| Executed(A setaddress12)
                                                  //| Executed(A setaddress13)
                                                  //| Executed(A setaddress14)
                                                  //| Executed(A setaddress15)
                                                  //| Executed(A setaddress16)
                                                  //| Executed(A setaddress17)
                                                  //| Executed(A setaddress18)
                                                  //| Executed(A setaddress19)
                                                  //| Executed(A setaddress20)
                                                  //| Executed(A setaddress21)
                                                  //| Executed(A setaddress22)
                                                  //| Executed(A setaddress23)
                                                  //| Executed(A setaddress24)
                                                  //| Executed(A setaddress25)
                                                  //| Executed(A setaddress26)
                                                  //| Executed(A setaddress27)
                                                  //| Executed(A setaddress28)
                                                  //| Executed(A setaddress29)
                                                  //| Executed(A setaddress30)
                                                  //| Executed(A setaddress31)
                                                  //| Executed(A setaddress32)
                                                  //| Executed(A setaddress33)
                                                  //| Executed(A setaddress34)
                                                  //| Executed(A setaddress35)
                                                  //| Executed(A setaddress36)
                                                  //| Executed(A setaddress37)
                                                  //| Executed(A setaddress38)
                                                  //| Executed(A setaddress39)
                                                  //| Executed(A setaddress40)
                                                  //| Executed(A setaddress41)
                                                  //| Executed(A setaddress42)
                                                  //| Executed(A setaddress43)
                                                  //| Executed(A setaddress44)
                                                  //| Executed(A setaddress45)
                                                  //| Executed(A setaddress46)
                                                  //| Executed(A setaddress47)
                                                  //| Executed(A setaddress48)
                                                  //| Executed(A setaddress49)
                                                  //| Executed(A setaddress50)
                                                  //| Executed(A setaddress51)
                                                  //| Executed(A setaddress52)
                                                  //| Executed(A setaddress53)
                                                  //| Executed(A setaddress54)
                                                  //| Executed(A setaddress55)
                                                  //| Executed(A setaddress56)
                                                  //| Executed(A setaddress57)
                                                  //| Executed(A setaddress58)
                                                  //| Executed(A setaddress59)
                                                  //| Executed(A setaddress60)
                                                  //| Executed(A setaddress61)
                                                  //| Executed(A setaddress62)
                                                  //| Executed(A setaddress63)
                                                  //| Executed(A setaddress64)
                                                  //| Executed(A setaddress65)
                                                  //| Executed(A setaddress66)
                                                  //| Executed(A setaddress67)
                                                  //| Executed(A setaddress68)
                                                  //| Executed(A setaddress69)
                                                  //| Executed(A setaddress70)
                                                  //| Executed(A setaddress71)
                                                  //| Executed(A setaddress72)
                                                  //| Executed(A setaddress73)
                                                  //| Executed(A setaddress74)
                                                  //| Executed(A setaddress75)
                                                  //| Executed(A setaddress76)
                                                  //| Executed(A setaddress77)
                                                  //| Executed(A setaddress78)
                                                  //| Executed(A setaddress79)
                                                  //| Executed(A setaddress80)
                                                  //| Executed(A setaddress81)
                                                  //| Executed(A setaddress82)
                                                  //| Executed(A setaddress83)
                                                  //| Executed(A setaddress84)
                                                  //| Executed(A setaddress85)
                                                  //| Executed(A setaddress86)
                                                  //| Executed(A setaddress87)
                                                  //| Executed(A setaddress88)
                                                  //| Executed(A setaddress89)
                                                  //| Executed(A setaddress90)
                                                  //| Executed(A setaddress91)
                                                  //| Executed(A setaddress92)
                                                  //| Executed(A setaddress93)
                                                  //| Executed(A setaddress94)
                                                  //| Executed(A setaddress95)
                                                  //| Executed(A setaddress96)
                                                  //| Executed(A setaddress97)
                                                  //| Executed(A setaddress98)
                                                  //| Executed(A setaddress99)
                                                  //| --- updatemarriage done ---
                                                  //| Executed(A updatemarriage0)
                                                  //| Executed(A updatemarriage1)
                                                  //| Executed(A updatemarriage2)
                                                  //| Executed(A updatemarriage3)
                                                  //| Executed(A updatemarriage4)
                                                  //| Executed(A updatemarriage5)
                                                  //| Executed(A updatemarriage6)
                                                  //| Executed(A updatemarriage7)
                                                  //| Executed(A updatemarriage8)
                                                  //| Executed(A updatemarriage9)
                                                  //| Executed(A updatemarriage10)
                                                  //| Executed(A updatemarriage11)
                                                  //| Executed(A updatemarriage12)
                                                  //| Executed(A updatemarriage13)
                                                  //| Executed(A updatemarriage14)
                                                  //| Executed(A updatemarriage15)
                                                  //| Executed(A updatemarriage16)
                                                  //| Executed(A updatemarriage17)
                                                  //| Executed(A updatemarriage18)
                                                  //| Executed(A updatemarriage19)
                                                  //| Executed(A updatemarriage20)
                                                  //| Executed(A updatemarriage21)
                                                  //| Executed(A updatemarriage22)
                                                  //| Executed(A updatemarriage23)
                                                  //| Executed(A updatemarriage24)
                                                  //| Executed(A updatemarriage25)
                                                  //| Executed(A updatemarriage26)
                                                  //| Executed(A updatemarriage27)
                                                  //| Executed(A updatemarriage28)
                                                  //| Executed(A updatemarriage29)
                                                  //| Executed(A updatemarriage30)
                                                  //| Executed(A updatemarriage31)
                                                  //| Executed(A updatemarriage32)
                                                  //| Executed(A updatemarriage33)
                                                  //| Executed(A updatemarriage34)
                                                  //| Executed(A updatemarriage35)
                                                  //| Executed(A updatemarriage36)
                                                  //| Executed(A updatemarriage37)
                                                  //| Executed(A updatemarriage38)
                                                  //| Executed(A updatemarriage39)
                                                  //| Executed(A updatemarriage40)
                                                  //| Executed(A updatemarriage41)
                                                  //| Executed(A updatemarriage42)
                                                  //| Executed(A updatemarriage43)
                                                  //| Executed(A updatemarriage44)
                                                  //| Executed(A updatemarriage45)
                                                  //| Executed(A updatemarriage46)
                                                  //| Executed(A updatemarriage47)
                                                  //| Executed(A updatemarriage48)
                                                  //| Executed(A updatemarriage49)
                                                  //| Executed(A updatemarriage50)
                                                  //| Executed(A updatemarriage51)
                                                  //| Executed(A updatemarriage52)
                                                  //| Executed(A updatemarriage53)
                                                  //| Executed(A updatemarriage54)
                                                  //| Executed(A updatemarriage55)
                                                  //| Executed(A updatemarriage56)
                                                  //| Executed(A updatemarriage57)
                                                  //| Executed(A updatemarriage58)
                                                  //| Executed(A updatemarriage59)
                                                  //| Executed(A updatemarriage60)
                                                  //| Executed(A updatemarriage61)
                                                  //| Executed(A updatemarriage62)
                                                  //| Executed(A updatemarriage63)
                                                  //| Executed(A updatemarriage64)
                                                  //| Executed(A updatemarriage65)
                                                  //| Executed(A updatemarriage66)
                                                  //| Executed(A updatemarriage67)
                                                  //| Executed(A updatemarriage68)
                                                  //| Executed(A updatemarriage69)
                                                  //| Executed(A updatemarriage70)
                                                  //| Executed(A updatemarriage71)
                                                  //| Executed(A updatemarriage72)
                                                  //| Executed(A updatemarriage73)
                                                  //| Executed(A updatemarriage74)
                                                  //| Executed(A updatemarriage75)
                                                  //| Executed(A updatemarriage76)
                                                  //| Executed(A updatemarriage77)
                                                  //| Executed(A updatemarriage78)
                                                  //| Executed(A updatemarriage79)
                                                  //| Executed(A updatemarriage80)
                                                  //| Executed(A updatemarriage81)
                                                  //| Executed(A updatemarriage82)
                                                  //| Executed(A updatemarriage83)
                                                  //| Executed(A updatemarriage84)
                                                  //| Executed(A updatemarriage85)
                                                  //| Executed(A updatemarriage86)
                                                  //| Executed(A updatemarriage87)
                                                  //| Executed(A updatemarriage88)
                                                  //| Executed(A updatemarriage89)
                                                  //| Executed(A updatemarriage90)
                                                  //| Executed(A updatemarriage91)
                                                  //| Executed(A updatemarriage92)
                                                  //| Executed(A updatemarriage93)
                                                  //| Executed(A updatemarriage94)
                                                  //| Executed(A updatemarriage95)
                                                  //| Executed(A updatemarriage96)
                                                  //| Executed(A updatemarriage97)
                                                  //| Executed(A updatemarriage98)
                                                  //| Executed(A updatemarriage99)
                                                  //| --- updatename done ---
                                                  //| Executed(A updatename0)
                                                  //| Executed(A updatename1)
                                                  //| Executed(A updatename2)
                                                  //| Executed(A updatename3)
                                                  //| Executed(A updatename4)
                                                  //| Executed(A updatename5)
                                                  //| Executed(A updatename6)
                                                  //| Executed(A updatename7)
                                                  //| Executed(A updatename8)
                                                  //| Executed(A updatename9)
                                                  //| Executed(A updatename10)
                                                  //| Executed(A updatename11)
                                                  //| Executed(A updatename12)
                                                  //| Executed(A updatename13)
                                                  //| Executed(A updatename14)
                                                  //| Executed(A updatename15)
                                                  //| Executed(A updatename16)
                                                  //| Executed(A updatename17)
                                                  //| Executed(A updatename18)
                                                  //| Executed(A updatename19)
                                                  //| Executed(A updatename20)
                                                  //| Executed(A updatename21)
                                                  //| Executed(A updatename22)
                                                  //| Executed(A updatename23)
                                                  //| Executed(A updatename24)
                                                  //| Executed(A updatename25)
                                                  //| Executed(A updatename26)
                                                  //| Executed(A updatename27)
                                                  //| Executed(A updatename28)
                                                  //| Executed(A updatename29)
                                                  //| Executed(A updatename30)
                                                  //| Executed(A updatename31)
                                                  //| Executed(A updatename32)
                                                  //| Executed(A updatename33)
                                                  //| Executed(A updatename34)
                                                  //| Executed(A updatename35)
                                                  //| Executed(A updatename36)
                                                  //| Executed(A updatename37)
                                                  //| Executed(A updatename38)
                                                  //| Executed(A updatename39)
                                                  //| Executed(A updatename40)
                                                  //| Executed(A updatename41)
                                                  //| Executed(A updatename42)
                                                  //| Executed(A updatename43)
                                                  //| Executed(A updatename44)
                                                  //| Executed(A updatename45)
                                                  //| Executed(A updatename46)
                                                  //| Executed(A updatename47)
                                                  //| Executed(A updatename48)
                                                  //| Executed(A updatename49)
                                                  //| Executed(A updatename50)
                                                  //| Executed(A updatename51)
                                                  //| Executed(A updatename52)
                                                  //| Executed(A updatename53)
                                                  //| Executed(A updatename54)
                                                  //| Executed(A updatename55)
                                                  //| Executed(A updatename56)
                                                  //| Executed(A updatename57)
                                                  //| Executed(A updatename58)
                                                  //| Executed(A updatename59)
                                                  //| Executed(A updatename60)
                                                  //| Executed(A updatename61)
                                                  //| Executed(A updatename62)
                                                  //| Executed(A updatename63)
                                                  //| Executed(A updatename64)
                                                  //| Executed(A updatename65)
                                                  //| Executed(A updatename66)
                                                  //| Executed(A updatename67)
                                                  //| Executed(A updatename68)
                                                  //| Executed(A updatename69)
                                                  //| Executed(A updatename70)
                                                  //| Executed(A updatename71)
                                                  //| Executed(A updatename72)
                                                  //| Executed(A updatename73)
                                                  //| Executed(A updatename74)
                                                  //| Executed(A updatename75)
                                                  //| Executed(A updatename76)
                                                  //| Executed(A updatename77)
                                                  //| Executed(A updatename78)
                                                  //| Executed(A updatename79)
                                                  //| Executed(A updatename80)
                                                  //| Executed(A updatename81)
                                                  //| Executed(A updatename82)
                                                  //| Executed(A updatename83)
                                                  //| Executed(A updatename84)
                                                  //| Executed(A updatename85)
                                                  //| Executed(A updatename86)
                                                  //| Executed(A updatename87)
                                                  //| Executed(A updatename88)
                                                  //| Executed(A updatename89)
                                                  //| Executed(A updatename90)
                                                  //| Executed(A updatename91)
                                                  //| Executed(A updatename92)
                                                  //| Executed(A updatename93)
                                                  //| Executed(A updatename94)
                                                  //| Executed(A updatename95)
                                                  //| Executed(A updatename96)
                                                  //| Executed(A updatename97)
                                                  //| Executed(A updatename98)
                                                  //| Executed(A updatename99)
                                                  //| res0: Boolean = true

}