package worksheets

import akka.dispatch.{ Await, Future }
import almhirt._
import almhirt.almvalidation.kit._
import almhirt.environment._
import test._
import almhirt.almfuture.inst._

object SequentialChunksWorksheet extends TestAlmhirtKit {
  implicit val atMost = akka.util.Duration(500, "ms")
                                                  //> atMost  : akka.util.FiniteDuration = 500 milliseconds
  inTestAlmhirt { almhirt =>
    implicit val executor = almhirt.environment.context.system.futureDispatcher
    val idsAndNamesAndAdresses = Vector((for (i <- 0 until 50) yield (i, almhirt.getUuid, "Name%s".format(i), "Address%s".format(i))): _*)

    val repo = almhirt.environment.repositories.getForAggregateRoot[TestPerson, TestPersonEvent].awaitResult.forceResult

    idsAndNamesAndAdresses.foreach(x => almhirt.executeTrackedCommand(NewTestPerson(x._2, x._3), "A insert%s".format(x._1.toString)))
    val insertStatesFutures = idsAndNamesAndAdresses.map(x => almhirt.getResultOperationStateFor("A insert%s".format(x._1.toString)))
    val insertStatesRes = AlmFuture.sequence(insertStatesFutures).awaitResult
    println("--- insert done ---")
    if (insertStatesRes.isFailure) println(insertStatesRes)
    insertStatesRes.foreach { insertStates =>
      insertStates.foreach(x => x fold (f => println(f), succ => println(succ)))
    }

    idsAndNamesAndAdresses.foreach(x => almhirt.executeTrackedCommand(SetTestPersonAddress(x._2, Some(1), x._4), "A setaddress%s".format(x._1.toString)))
    val update1StatesFutures = idsAndNamesAndAdresses.map(x => almhirt.getResultOperationStateFor("A setaddress%s".format(x._1.toString)))
    val update1StatesRes = AlmFuture.sequence(update1StatesFutures).awaitResult
    println("--- setaddress done ---")
    if (update1StatesRes.isFailure) println(update1StatesRes)
    update1StatesRes.foreach { updateStates =>
      updateStates.foreach(x => x fold (f => println(f), succ => println(succ)))
    }

    idsAndNamesAndAdresses.foreach(x => almhirt.executeTrackedCommand(MoveBecauseOfMarriage(x._2, Some(2), "namemarriage%s".format(x._3), "addressmarriage%s".format(x._3)), "A updatemarriage%s".format(x._1.toString)))
    val update2StatesFutures = idsAndNamesAndAdresses.map(x => almhirt.getResultOperationStateFor("A updatemarriage%s".format(x._1.toString)))
    val update2StatesRes = AlmFuture.sequence(update2StatesFutures).awaitResult
    println("--- updatemarriage done ---")
    if (update2StatesRes.isFailure) println(update2StatesRes)
    update2StatesRes.foreach { updateStates =>
      updateStates.foreach(x => x fold (f => println(f), succ => println(succ)))
    }

    idsAndNamesAndAdresses.foreach(x => almhirt.executeTrackedCommand(ChangeTestPersonName(x._2, Some(4), "new%s".format(x._3)), "A updatename%s".format(x._1.toString)))
    val update3StatesFutures = idsAndNamesAndAdresses.map(x => almhirt.getResultOperationStateFor("A updatename%s".format(x._1.toString)))
    val update3StatesRes = AlmFuture.sequence(update3StatesFutures).awaitResult
    println("--- updatename done ---")
    if (update3StatesRes.isFailure) println(update3StatesRes)

    //    almhirt.environment.eventLog.getAllEvents.awaitResult.forceResult.foreach(println)
    //    AlmFuture.sequence(idsAndNamesAndAdresses.map(x => repo.get(x._2))).awaitResult.forceResult.foreach(println)


    update3StatesRes.map { updateStates =>
      updateStates.foreach(x => x fold (f => println(f), succ => println(succ)))
      updateStates
    }.fold(
      f => false,
      succ => succ.forall(_.isSuccess) && succ.forall(_.forceResult.isFinishedSuccesfully))
  }                                               //> cmd: Some(StringTrackingTicket(A insert0))
                                                  //| cmd: Some(StringTrackingTicket(A insert1))
                                                  //| cmd: Some(StringTrackingTicket(A insert2))
                                                  //| cmd: Some(StringTrackingTicket(A insert3))
                                                  //| cmd: Some(StringTrackingTicket(A insert4))
                                                  //| cmd: Some(StringTrackingTicket(A insert5))
                                                  //| cmd: Some(StringTrackingTicket(A insert6))
                                                  //| cmd: Some(StringTrackingTicket(A insert7))
                                                  //| cmd: Some(StringTrackingTicket(A insert8))
                                                  //| cmd: Some(StringTrackingTicket(A insert9))
                                                  //| cmd: Some(StringTrackingTicket(A insert10))
                                                  //| cmd: Some(StringTrackingTicket(A insert11))
                                                  //| cmd: Some(StringTrackingTicket(A insert12))
                                                  //| cmd: Some(StringTrackingTicket(A insert13))
                                                  //| cmd: Some(StringTrackingTicket(A insert14))
                                                  //| cmd: Some(StringTrackingTicket(A insert15))
                                                  //| cmd: Some(StringTrackingTicket(A insert16))
                                                  //| cmd: Some(StringTrackingTicket(A insert17))
                                                  //| cmd: Some(StringTrackingTicket(A insert18))
                                                  //| cmd: Some(StringTrackingTicket(A insert19))
                                                  //| cmd: Some(StringTrackingTicket(A insert20))
                                                  //| cmd: Some(StringTrackingTicket(A insert21))
                                                  //| cmd: Some(StringTrackingTicket(A insert22))
                                                  //| cmd: Some(StringTrackingTicket(A insert23))
                                                  //| cmd: Some(StringTrackingTicket(A insert24))
                                                  //| cmd: Some(StringTrackingTicket(A insert25))
                                                  //| cmd: Some(StringTrackingTicket(A insert26))
                                                  //| cmd: Some(StringTrackingTicket(A insert27))
                                                  //| cmd: Some(StringTrackingTicket(A insert28))
                                                  //| cmd: Some(StringTrackingTicket(A insert29))
                                                  //| cmd: Some(StringTrackingTicket(A insert30))
                                                  //| cmd: Some(StringTrackingTicket(A insert31))
                                                  //| cmd: Some(StringTrackingTicket(A insert32))
                                                  //| cmd: Some(StringTrackingTicket(A insert33))
                                                  //| cmd: Some(StringTrackingTicket(A insert34))
                                                  //| cmd: Some(StringTrackingTicket(A insert35))
                                                  //| cmd: Some(StringTrackingTicket(A insert36))
                                                  //| cmd: Some(StringTrackingTicket(A insert37))
                                                  //| cmd: Some(StringTrackingTicket(A insert38))
                                                  //| cmd: Some(StringTrackingTicket(A insert39))
                                                  //| cmd: Some(StringTrackingTicket(A insert40))
                                                  //| cmd: Some(StringTrackingTicket(A insert41))
                                                  //| cmd: Some(StringTrackingTicket(A insert42))
                                                  //| cmd: Some(StringTrackingTicket(A insert43))
                                                  //| cmd: Some(StringTrackingTicket(A insert44))
                                                  //| cmd: Some(StringTrackingTicket(A insert45))
                                                  //| cmd: Some(StringTrackingTicket(A insert46))
                                                  //| cmd: Some(StringTrackingTicket(A insert47))
                                                  //| cmd: Some(StringTrackingTicket(A insert48))
                                                  //| cmd: Some(StringTrackingTicket(A insert49))
                                                  //| --- insert done ---
                                                  //| Executed(StringTrackingTicket(A insert0))
                                                  //| Executed(StringTrackingTicket(A insert1))
                                                  //| Executed(StringTrackingTicket(A insert2))
                                                  //| Executed(StringTrackingTicket(A insert3))
                                                  //| Executed(StringTrackingTicket(A insert4))
                                                  //| Executed(StringTrackingTicket(A insert5))
                                                  //| Executed(StringTrackingTicket(A insert6))
                                                  //| Executed(StringTrackingTicket(A insert7))
                                                  //| Executed(StringTrackingTicket(A insert8))
                                                  //| Executed(StringTrackingTicket(A insert9))
                                                  //| Executed(StringTrackingTicket(A insert10))
                                                  //| Executed(StringTrackingTicket(A insert11))
                                                  //| Executed(StringTrackingTicket(A insert12))
                                                  //| Executed(StringTrackingTicket(A insert13))
                                                  //| Executed(StringTrackingTicket(A insert14))
                                                  //| Executed(StringTrackingTicket(A insert15))
                                                  //| Executed(StringTrackingTicket(A insert16))
                                                  //| Executed(StringTrackingTicket(A insert17))
                                                  //| Executed(StringTrackingTicket(A insert18))
                                                  //| Executed(StringTrackingTicket(A insert19))
                                                  //| Executed(StringTrackingTicket(A insert20))
                                                  //| Executed(StringTrackingTicket(A insert21))
                                                  //| Executed(StringTrackingTicket(A insert22))
                                                  //| Executed(StringTrackingTicket(A insert23))
                                                  //| Executed(StringTrackingTicket(A insert24))
                                                  //| Executed(StringTrackingTicket(A insert25))
                                                  //| Executed(StringTrackingTicket(A insert26))
                                                  //| Executed(StringTrackingTicket(A insert27))
                                                  //| Executed(StringTrackingTicket(A insert28))
                                                  //| Executed(StringTrackingTicket(A insert29))
                                                  //| Executed(StringTrackingTicket(A insert30))
                                                  //| Executed(StringTrackingTicket(A insert31))
                                                  //| Executed(StringTrackingTicket(A insert32))
                                                  //| Executed(StringTrackingTicket(A insert33))
                                                  //| Executed(StringTrackingTicket(A insert34))
                                                  //| Executed(StringTrackingTicket(A insert35))
                                                  //| Executed(StringTrackingTicket(A insert36))
                                                  //| Executed(StringTrackingTicket(A insert37))
                                                  //| Executed(StringTrackingTicket(A insert38))
                                                  //| Executed(StringTrackingTicket(A insert39))
                                                  //| Executed(StringTrackingTicket(A insert40))
                                                  //| Executed(StringTrackingTicket(A insert41))
                                                  //| Executed(StringTrackingTicket(A insert42))
                                                  //| Executed(StringTrackingTicket(A insert43))
                                                  //| Executed(StringTrackingTicket(A insert44))
                                                  //| Executed(StringTrackingTicket(A insert45))
                                                  //| Executed(StringTrackingTicket(A insert46))
                                                  //| Executed(StringTrackingTicket(A insert47))
                                                  //| Executed(StringTrackingTicket(A insert48))
                                                  //| Executed(StringTrackingTicket(A insert49))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress0))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress1))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress2))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress3))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress4))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress5))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress6))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress7))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress8))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress9))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress10))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress11))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress12))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress13))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress14))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress15))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress16))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress17))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress18))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress19))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress20))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress21))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress22))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress23))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress24))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress25))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress26))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress27))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress28))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress29))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress30))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress31))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress32))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress33))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress34))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress35))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress36))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress37))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress38))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress39))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress40))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress41))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress42))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress43))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress44))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress45))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress46))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress47))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress48))
                                                  //| cmd: Some(StringTrackingTicket(A setaddress49))
                                                  //| --- setaddress done ---
                                                  //| Executed(StringTrackingTicket(A setaddress0))
                                                  //| Executed(StringTrackingTicket(A setaddress1))
                                                  //| Executed(StringTrackingTicket(A setaddress2))
                                                  //| Executed(StringTrackingTicket(A setaddress3))
                                                  //| Executed(StringTrackingTicket(A setaddress4))
                                                  //| Executed(StringTrackingTicket(A setaddress5))
                                                  //| Executed(StringTrackingTicket(A setaddress6))
                                                  //| Executed(StringTrackingTicket(A setaddress7))
                                                  //| Executed(StringTrackingTicket(A setaddress8))
                                                  //| Executed(StringTrackingTicket(A setaddress9))
                                                  //| Executed(StringTrackingTicket(A setaddress10))
                                                  //| Executed(StringTrackingTicket(A setaddress11))
                                                  //| Executed(StringTrackingTicket(A setaddress12))
                                                  //| Executed(StringTrackingTicket(A setaddress13))
                                                  //| Executed(StringTrackingTicket(A setaddress14))
                                                  //| Executed(StringTrackingTicket(A setaddress15))
                                                  //| Executed(StringTrackingTicket(A setaddress16))
                                                  //| Executed(StringTrackingTicket(A setaddress17))
                                                  //| Executed(StringTrackingTicket(A setaddress18))
                                                  //| Executed(StringTrackingTicket(A setaddress19))
                                                  //| Executed(StringTrackingTicket(A setaddress20))
                                                  //| Executed(StringTrackingTicket(A setaddress21))
                                                  //| Executed(StringTrackingTicket(A setaddress22))
                                                  //| Executed(StringTrackingTicket(A setaddress23))
                                                  //| Executed(StringTrackingTicket(A setaddress24))
                                                  //| Executed(StringTrackingTicket(A setaddress25))
                                                  //| Executed(StringTrackingTicket(A setaddress26))
                                                  //| Executed(StringTrackingTicket(A setaddress27))
                                                  //| Executed(StringTrackingTicket(A setaddress28))
                                                  //| Executed(StringTrackingTicket(A setaddress29))
                                                  //| Executed(StringTrackingTicket(A setaddress30))
                                                  //| Executed(StringTrackingTicket(A setaddress31))
                                                  //| Executed(StringTrackingTicket(A setaddress32))
                                                  //| Executed(StringTrackingTicket(A setaddress33))
                                                  //| Executed(StringTrackingTicket(A setaddress34))
                                                  //| Executed(StringTrackingTicket(A setaddress35))
                                                  //| Executed(StringTrackingTicket(A setaddress36))
                                                  //| Executed(StringTrackingTicket(A setaddress37))
                                                  //| Executed(StringTrackingTicket(A setaddress38))
                                                  //| Executed(StringTrackingTicket(A setaddress39))
                                                  //| Executed(StringTrackingTicket(A setaddress40))
                                                  //| Executed(StringTrackingTicket(A setaddress41))
                                                  //| Executed(StringTrackingTicket(A setaddress42))
                                                  //| Executed(StringTrackingTicket(A setaddress43))
                                                  //| Executed(StringTrackingTicket(A setaddress44))
                                                  //| Executed(StringTrackingTicket(A setaddress45))
                                                  //| Executed(StringTrackingTicket(A setaddress46))
                                                  //| Executed(StringTrackingTicket(A setaddress47))
                                                  //| Executed(StringTrackingTicket(A setaddress48))
                                                  //| Executed(StringTrackingTicket(A setaddress49))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage0))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage1))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage2))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage3))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage4))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage5))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage6))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage7))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage8))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage9))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage10))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage11))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage12))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage13))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage14))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage15))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage16))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage17))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage18))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage19))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage20))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage21))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage22))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage23))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage24))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage25))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage26))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage27))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage28))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage29))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage30))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage31))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage32))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage33))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage34))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage35))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage36))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage37))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage38))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage39))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage40))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage41))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage42))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage43))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage44))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage45))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage46))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage47))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage48))
                                                  //| cmd: Some(StringTrackingTicket(A updatemarriage49))
                                                  //| --- updatemarriage done ---
                                                  //| Executed(StringTrackingTicket(A updatemarriage0))
                                                  //| Executed(StringTrackingTicket(A updatemarriage1))
                                                  //| Executed(StringTrackingTicket(A updatemarriage2))
                                                  //| Executed(StringTrackingTicket(A updatemarriage3))
                                                  //| Executed(StringTrackingTicket(A updatemarriage4))
                                                  //| Executed(StringTrackingTicket(A updatemarriage5))
                                                  //| Executed(StringTrackingTicket(A updatemarriage6))
                                                  //| Executed(StringTrackingTicket(A updatemarriage7))
                                                  //| Executed(StringTrackingTicket(A updatemarriage8))
                                                  //| Executed(StringTrackingTicket(A updatemarriage9))
                                                  //| Executed(StringTrackingTicket(A updatemarriage10))
                                                  //| Executed(StringTrackingTicket(A updatemarriage11))
                                                  //| Executed(StringTrackingTicket(A updatemarriage12))
                                                  //| Executed(StringTrackingTicket(A updatemarriage13))
                                                  //| Executed(StringTrackingTicket(A updatemarriage14))
                                                  //| Executed(StringTrackingTicket(A updatemarriage15))
                                                  //| Executed(StringTrackingTicket(A updatemarriage16))
                                                  //| Executed(StringTrackingTicket(A updatemarriage17))
                                                  //| Executed(StringTrackingTicket(A updatemarriage18))
                                                  //| Executed(StringTrackingTicket(A updatemarriage19))
                                                  //| Executed(StringTrackingTicket(A updatemarriage20))
                                                  //| Executed(StringTrackingTicket(A updatemarriage21))
                                                  //| Executed(StringTrackingTicket(A updatemarriage22))
                                                  //| Executed(StringTrackingTicket(A updatemarriage23))
                                                  //| Executed(StringTrackingTicket(A updatemarriage24))
                                                  //| Executed(StringTrackingTicket(A updatemarriage25))
                                                  //| Executed(StringTrackingTicket(A updatemarriage26))
                                                  //| Executed(StringTrackingTicket(A updatemarriage27))
                                                  //| Executed(StringTrackingTicket(A updatemarriage28))
                                                  //| Executed(StringTrackingTicket(A updatemarriage29))
                                                  //| Executed(StringTrackingTicket(A updatemarriage30))
                                                  //| Executed(StringTrackingTicket(A updatemarriage31))
                                                  //| Executed(StringTrackingTicket(A updatemarriage32))
                                                  //| Executed(StringTrackingTicket(A updatemarriage33))
                                                  //| Executed(StringTrackingTicket(A updatemarriage34))
                                                  //| Executed(StringTrackingTicket(A updatemarriage35))
                                                  //| Executed(StringTrackingTicket(A updatemarriage36))
                                                  //| Executed(StringTrackingTicket(A updatemarriage37))
                                                  //| Executed(StringTrackingTicket(A updatemarriage38))
                                                  //| Executed(StringTrackingTicket(A updatemarriage39))
                                                  //| Executed(StringTrackingTicket(A updatemarriage40))
                                                  //| Executed(StringTrackingTicket(A updatemarriage41))
                                                  //| Executed(StringTrackingTicket(A updatemarriage42))
                                                  //| Executed(StringTrackingTicket(A updatemarriage43))
                                                  //| Executed(StringTrackingTicket(A updatemarriage44))
                                                  //| Executed(StringTrackingTicket(A updatemarriage45))
                                                  //| Executed(StringTrackingTicket(A updatemarriage46))
                                                  //| Executed(StringTrackingTicket(A updatemarriage47))
                                                  //| Executed(StringTrackingTicket(A updatemarriage48))
                                                  //| Executed(StringTrackingTicket(A updatemarriage49))
                                                  //| cmd: Some(StringTrackingTicket(A updatename0))
                                                  //| cmd: Some(StringTrackingTicket(A updatename1))
                                                  //| cmd: Some(StringTrackingTicket(A updatename2))
                                                  //| cmd: Some(StringTrackingTicket(A updatename3))
                                                  //| cmd: Some(StringTrackingTicket(A updatename4))
                                                  //| cmd: Some(StringTrackingTicket(A updatename5))
                                                  //| cmd: Some(StringTrackingTicket(A updatename6))
                                                  //| cmd: Some(StringTrackingTicket(A updatename7))
                                                  //| cmd: Some(StringTrackingTicket(A updatename8))
                                                  //| cmd: Some(StringTrackingTicket(A updatename9))
                                                  //| cmd: Some(StringTrackingTicket(A updatename10))
                                                  //| cmd: Some(StringTrackingTicket(A updatename11))
                                                  //| cmd: Some(StringTrackingTicket(A updatename12))
                                                  //| cmd: Some(StringTrackingTicket(A updatename13))
                                                  //| cmd: Some(StringTrackingTicket(A updatename14))
                                                  //| cmd: Some(StringTrackingTicket(A updatename15))
                                                  //| cmd: Some(StringTrackingTicket(A updatename16))
                                                  //| cmd: Some(StringTrackingTicket(A updatename17))
                                                  //| cmd: Some(StringTrackingTicket(A updatename18))
                                                  //| cmd: Some(StringTrackingTicket(A updatename19))
                                                  //| cmd: Some(StringTrackingTicket(A updatename20))
                                                  //| cmd: Some(StringTrackingTicket(A updatename21))
                                                  //| cmd: Some(StringTrackingTicket(A updatename22))
                                                  //| cmd: Some(StringTrackingTicket(A updatename23))
                                                  //| cmd: Some(StringTrackingTicket(A updatename24))
                                                  //| cmd: Some(StringTrackingTicket(A updatename25))
                                                  //| cmd: Some(StringTrackingTicket(A updatename26))
                                                  //| cmd: Some(StringTrackingTicket(A updatename27))
                                                  //| cmd: Some(StringTrackingTicket(A updatename28))
                                                  //| cmd: Some(StringTrackingTicket(A updatename29))
                                                  //| cmd: Some(StringTrackingTicket(A updatename30))
                                                  //| cmd: Some(StringTrackingTicket(A updatename31))
                                                  //| cmd: Some(StringTrackingTicket(A updatename32))
                                                  //| cmd: Some(StringTrackingTicket(A updatename33))
                                                  //| cmd: Some(StringTrackingTicket(A updatename34))
                                                  //| cmd: Some(StringTrackingTicket(A updatename35))
                                                  //| cmd: Some(StringTrackingTicket(A updatename36))
                                                  //| cmd: Some(StringTrackingTicket(A updatename37))
                                                  //| cmd: Some(StringTrackingTicket(A updatename38))
                                                  //| cmd: Some(StringTrackingTicket(A updatename39))
                                                  //| cmd: Some(StringTrackingTicket(A updatename40))
                                                  //| cmd: Some(StringTrackingTicket(A updatename41))
                                                  //| cmd: Some(StringTrackingTicket(A updatename42))
                                                  //| cmd: Some(StringTrackingTicket(A updatename43))
                                                  //| cmd: Some(StringTrackingTicket(A updatename44))
                                                  //| cmd: Some(StringTrackingTicket(A updatename45))
                                                  //| cmd: Some(StringTrackingTicket(A updatename46))
                                                  //| cmd: Some(StringTrackingTicket(A updatename47))
                                                  //| cmd: Some(StringTrackingTicket(A updatename48))
                                                  //| cmd: Some(StringTrackingTicket(A updatename49))
                                                  //| --- updatename done ---
                                                  //| Executed(StringTrackingTicket(A updatename0))
                                                  //| Executed(StringTrackingTicket(A updatename1))
                                                  //| Executed(StringTrackingTicket(A updatename2))
                                                  //| Executed(StringTrackingTicket(A updatename3))
                                                  //| Executed(StringTrackingTicket(A updatename4))
                                                  //| Executed(StringTrackingTicket(A updatename5))
                                                  //| Executed(StringTrackingTicket(A updatename6))
                                                  //| Executed(StringTrackingTicket(A updatename7))
                                                  //| Executed(StringTrackingTicket(A updatename8))
                                                  //| Executed(StringTrackingTicket(A updatename9))
                                                  //| Executed(StringTrackingTicket(A updatename10))
                                                  //| Executed(StringTrackingTicket(A updatename11))
                                                  //| Executed(StringTrackingTicket(A updatename12))
                                                  //| Executed(StringTrackingTicket(A updatename13))
                                                  //| Executed(StringTrackingTicket(A updatename14))
                                                  //| Executed(StringTrackingTicket(A updatename15))
                                                  //| Executed(StringTrackingTicket(A updatename16))
                                                  //| Executed(StringTrackingTicket(A updatename17))
                                                  //| Executed(StringTrackingTicket(A updatename18))
                                                  //| Executed(StringTrackingTicket(A updatename19))
                                                  //| Executed(StringTrackingTicket(A updatename20))
                                                  //| Executed(StringTrackingTicket(A updatename21))
                                                  //| Executed(StringTrackingTicket(A updaten
                                                  //| Output exceeds cutoff limit.

}